# Generated by Django 4.2.25 on 2025-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLayanan',
            fields=[
                ('id_area_layanan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_area', models.CharField(max_length=100, unique=True)),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'area_layanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisJasa',
            fields=[
                ('id_jenis_jasa', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jasa', models.CharField(max_length=100, unique=True)),
                ('biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'jenis_jasa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisPerangkat',
            fields=[
                ('id_jenis_perangkat', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'jenis_perangkat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('id_langganan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('status_langganan', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'langganan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id_metode_bayar', models.AutoField(primary_key=True, serialize=False)),
                ('nama_metode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'metode_pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaketLayanan',
            fields=[
                ('id_paket', models.AutoField(primary_key=True, serialize=False)),
                ('nama_paket', models.CharField(max_length=100, unique=True)),
                ('kecepatan_mbps', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paket_layanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('alamat_pemasangan', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_daftar', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'pelanggan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_bayar', models.DateTimeField()),
                ('periode_tagihan', models.DateField(blank=True, null=True)),
                ('status_pembayaran', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PemesananJasa',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_jadwal', models.DateField(blank=True, null=True)),
                ('status_pemesanan', models.CharField(max_length=18)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pemesanan_jasa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenempatanPerangkat',
            fields=[
                ('id_penempatan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pasang', models.DateField(blank=True, null=True)),
                ('status_perangkat', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'penempatan_perangkat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perangkat',
            fields=[
                ('id_perangkat', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('merk_model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'perangkat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatTestingWifi',
            fields=[
                ('id_testing', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_testing', models.DateTimeField(auto_now_add=True)),
                ('download_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upload_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ping_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'riwayat_testing_wifi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teknisi',
            fields=[
                ('id_teknisi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_teknisi', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role_akses', models.CharField(max_length=7)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'teknisi',
                'managed': False,
            },
        ),
    ]