# Generated by Django 4.2.25 on 2025-11-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langganan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paketlayanan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='riwayattestingwifi',
            options={'managed': True},
        ),
    ]
