# Generated by Django 4.2.25 on 2025-11-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_wifi', '0002_alter_langganan_options_alter_paketlayanan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='langganan',
            name='id_paket',
            field=models.ForeignKey(blank=True, db_column='id_paket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='layanan_wifi.paketlayanan'),
        ),
        migrations.AddField(
            model_name='langganan',
            name='id_pelanggan',
            field=models.ForeignKey(blank=True, db_column='id_pelanggan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='layanan_wifi.pelanggan'),
        ),
        migrations.AddField(
            model_name='riwayattestingwifi',
            name='id_langganan',
            field=models.ForeignKey(blank=True, db_column='id_langganan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='layanan_wifi.langganan'),
        ),
    ]
