<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-11-13 10:56
=======
<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-11-20 11:49
=======
# Generated by Django 4.2.25 on 2025-11-19 02:47
>>>>>>> ddb82aa0ecfaa73607c7862bb1c280af9af1382e
>>>>>>> 5871e0f2112f2a668ba64d308a3c3aa076281f3f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_wifi', '0003_langganan_id_paket_langganan_id_pelanggan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langganan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paketlayanan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='riwayattestingwifi',
            options={'managed': False},
        ),
    ]
