
# Generated by Django 4.2.25 on 2025-11-20 11:49
# Generated by Django 4.2.25 on 2025-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_wifi', '0003_langganan_id_paket_langganan_id_pelanggan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langganan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paketlayanan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='riwayattestingwifi',
            options={'managed': False},
        ),
    ]
