# Generated by Django 4.2.25 on 2025-11-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_wifi', '0004_alter_langganan_options_alter_paketlayanan_options_and_more'),
    ]

    operations = [
    ]
